################################################################################
# ITEMS RANDOM BY SKYFLYER
################################################################################

BLACK_LIST = [:LOPUNNYTE, :SACREDASH, :BLACKFLUTE, :WHITEFLUTE, :HONEY, :ESCAPEROPE, :REDSHARD, 
  :YELLOWSHARD, :BLUESHARD, :GREENSHARD, :REDAPRICORN, :YLWAPRICORN, :BLUAPRICORN, 
  :GRNAPRICORN, :PNKAPRICORN, :PNKAPRICORN, :WHTAPRICORN, :BLKAPRICORN, 
  :SLOWPOKETAIL, :GROWTHMULCH, :DAMPMULCH, :STABLEMULCH, :GOOEYMULCH, :SHOALSALT, 
  :SHOALSHELL, :ODDKEYSTONE, :EXPSHARE, :SOULDEW, :DEEPSEATOOTH, :DEEPSEASCALE, 
  :ADAMANTORB, :LUSTROUSORB, :GRISEOUSORB, :DOUSEDRIVE, :SHOCKDRIVE, :BURNDRIVE, 
  :CHILLDRIVE, :DRAGONSCALE, :UPGRADE, :DUBIOUSDISC, :PROTECTOR, :ELECTIRIZER, 
  :MAGMARIZER, :REAPERCLOTH, :PRISMSCALE, :OVALSTONE, :REDSCARF, :BLUESCARF, 
  :PINKSCARF, :GREENSCARF, :YELLOWSCARF, :SAFARIBALL, :HM01, :HM02, :HM03, :HM04, 
  :HM05, :HM06, :RAZZBERRY, :BLUKBERRY, :NANABBERRY, :WEPEARBERRY, :PINAPBERRY, 
  :CORNNBERRY, :MAGOSTBERRY, :RABUTABERRY, :NOMELBERRY, :SPELONBERRY, :PAMTREBERRY, 
  :WATMELBERRY, :DURINBERRY, :BELUEBERRY, :GRASSMAIL, :FLAMEMAIL, :BUBBLEMAIL, 
  :BLOOMMAIL, :TUNNELMAIL, :STEELMAIL, :HEARTMAIL, :SNOWMAIL, :SPACEMAIL, :AIRMAIL, 
  :MOSAICMAIL, :BRICKMAIL, :RESETURGE, :XATTACK3, :XATTACK6, :XDEFEND3, :XDEFEND6, 
  :XSPECIAL3, :XSPECIAL6, :XSPEED3, :XSPEED6, :XSPDEF3, :XSPDEF6, :XACCURACY3, 
  :XACCURACY6, :DIREHIT2, :DIREHIT3, :ITEMURGE, :ITEMDROP, :BLUEFLUTE, :YELLOWFLUTE, 
  :REDFLUTE, :POKEDOLL, :POKETOY, :BICYCLE, :OLDROD, :GOODROD, :SUPERROD, 
  :ITEMFINDER, :DOWSINGMACHINE, :POKERADAR, :TOWNMAP, :POKEFLUTE, :COINCASE, 
  :SOOTSACK, :SILPHSCOPE, :DEVONSCOPE, :SQUIRTBOTTLE, :SPRAYDUCK, :WAILMERPAIL, 
  :GRACIDEA, :AURORATICKET, :OLDSEAMAP, :DNASPLICERS, :REVEALGLASS, :OVALCHARM, 
  :SHINYCHARM, :POKEVIAL, :TICKETBARCO, :INCUBADORA, :BONOBICI, :EXPALL, 
  :ILUMINADOR, :TALADOR, :Cenizas, :VISORSILPH, :LLAVEROCKET, :RESGUARDO, 
  :Escalada, :MUNECOCOPIONA, :Anillo, :TESECRETO, :TMAGN1, :TMAGN2, :LlaveCapilla,
  :Hierbas, :Despetrificante, :Rosa, :PaseDorado, :Ganzua, :TarjetaMagnetica, 
  :EscamaDorada, :Dinamita, :Gafas, :ManzanaDorada, :PaseCine, :Fusible, 
  :BRAVIARITA, :CONTROLES, :CartaJara, :RAMENPICANTE, :FOTOGATLING, :FOTOGATLING2,
  :KINGLERITA, :BUTTERFREEITA, :MACHAMPITA, :LAPRASITA, :GARBODORITA, 
  :CORVIKNIGHTITA, :ORBEETLEITA, :DREDNAWITA, :COALOSSALITA, :FLAPPLETUNITA, 
  :SANDACONDITA, :TOXTRICITITA, :CENTISKORCHITA, :HATTERENITA, :GRIMMSNARLITA, 
  :ALCREMITA, :COPPERAJITA, :DURALUDONITA, :ALAKAZAMITA, :GENGARITA, :KANGASKHANITA, 
  :PINSIRITA, :GYARADOSITA, :AERODACTYLITA, :AMPHAROSITA, :SCIZORITA, :HERACROSSITA, 
  :HOUNDOOMITA, :GARDEVOIRITA, :AGGRONITA, :MEDICHAMITA, :MANECTRITA, :ABSOLITA, 
  :LUCARITA, :BEEDRILLITA, :PIDGEOTITA, :SLOWBRITA, :STEELIXITA, :SABLEYITA, 
  :SHARPEDITA, :CAMERUPTITA, :ALTARITA, :GLALIEITA, :GALLADITA, :BRAZALESPIRITUAL, 
  :POKERIDER, :SEVIPERITA, :GASTESLITA, :LUNAYITA, :NARVALORITA, :GRENINJITA, 
  :LENSOFTRUTH, :BLAZIKENITE, :PIKACHUITA, :SUPERCOMIDA, :POKESENCIAREFINADA, 
  :VENUSAURITE, :CHARIZARDITEY, :BLASTOISINITE, :SURFMONTURA, :TYRANITARITE, 
  :SCEPTILITE, :SWAMPERTITE, :LLAVESUPERSECRETA, :CHARIZARDITEX, :CAMPANADORADA, 
  :CAMPANAPLATEADA, :DEXNAV, :CRISTALPRISMA, :LLAVECAMION, :OFRENDAPRISMATICA, 
  :SALAMENCITE, :METAGROSSITE, :GARCHOMPITE, :PLUMAARTICUNO, :PLUMAZAPDOS, 
  :PLUMAMOLTRES, :ANTICRITICO, :DIPLOMA, :OA, :OB, :OC, :OD, :OE, :OF, :OG, :OH, 
  :OI, :OJ, :OK, :OL, :OM, :ON, :OO, :OP, :OQ, :OR, :OS, :OT, :OU, :OV, :OW, :OX, 
  :OY, :OZ, :OAA, :OBB, :OCC, :ODD, :OEE, :OFF, :OGG, :OHH, :OII, :OJJ, :OKK, 
  :OLL, :OMM, :ONN, :OOO, :OPP, :OEE, :OTT, :SPORTBALL]


MTLIST_RANDOM = [:TM01, :TM02, :TM03, :TM04, :TM05, :TM06, :TM07, :TM08, :TM09, :TM10,
  :TM11, :TM12, :TM13, :TM14, :TM15, :TM16, :TM17, :TM18, :TM19, :TM20, :TM21,
  :TM22, :TM23, :TM24, :TM25, :TM26, :TM27, :TM28, :TM29, :TM30, :TM31, :TM32,
  :TM33, :TM34, :TM35, :TM36, :TM37, :TM38, :TM39, :TM40, :TM41, :TM42, :TM43,
  :TM44, :TM45, :TM46, :TM47, :TM48, :TM49, :TM50, :TM51, :TM52, :TM53, :TM54,
  :TM55, :TM56, :TM57, :TM58, :TM59, :TM60, :TM61, :TM62, :TM63, :TM64, :TM65,
  :TM66, :TM67, :TM68, :TM69, :TM70, :TM71, :TM72, :TM73, :TM74, :TM75, :TM76,
  :TM77, :TM78, :TM79, :TM80, :TM81, :TM82, :TM83, :TM84, :TM85, :TM86, :TM87,
  :TM88, :TM89, :TM90, :TM91, :TM92, :TM93, :TM94, :TM95, :TM96, :TM97, :TM98,
  :TM99, :TM100, :TM101, :TM102, :TM103, :TM104, :TM105, :TM106, :TM107, :TM108]

################################################################################
################################################################################ 


# Al llamar a esta función, si el interruptor ITEMS_RANDOM está activo, el objeto
# que encontramos es uno al azar.
def getItemRandomFromPokeball()
  objeto_elegido = 0
  loop do
    objeto_elegido = rand(PBItems.maxValue)
    for i in BLACK_LIST
      item=getID(PBItems,i)
      enBlackList = true if objeto_elegido==item
      break if enBlackList
    end
    for i in MTLIST_RANDOM
      item=getID(PBItems,i)
      mtRepetida = true if (objeto_elegido==item && $PokemonBag.pbHasItem?(objeto_elegido))
      break if mtRepetida
    end
    break if !enBlackList && !mtRepetida
  end
  Kernel.pbItemBall(objeto_elegido)
end
